spring.application.name=LearningAnnotations
server.port=0
# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/Demo
spring.datasource.username=postgres
spring.datasource.password=Addie

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


my.data=prodData